language: go
go:
- 1.5
branches:
  only:
  - master
  - deployment

before_script:
- sudo add-apt-repository ppa:rethinkdb/ppa -y
- source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME
  main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list;
- wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -;
- sudo apt-get update;
- sudo apt-get -y install rethinkdb;
- rethinkdb &

global:
- secure: f2/WiAYS5S2NcZTeyjvuJauHXNXhryui2teKZkhmebk+C9uIWpz0pvdSHXw6kTKw1dm8sxS30HvEAGOTrT0LwuoG3DUDjk5Y1oefiGEgkC8/8lAO93lXR7L3+2AhEUc2eyI9gDWy993GeH8z+FUBkSGH4l2m5rtL5eNny1VGV7ACTaMx8RWvRV6fhICyKhDQLT6qha4PQd+Wy6J1vJTte/VHrIfFUmedrQg8hzTjXKpfF/cQzcUIsYf6/e/mEAVsK+bQQ1P+LogUT/rLNZ1zvnATzGFgDZMQLXP3PhWi4mrNxg43GnEE2Mb6Qy1rLZUQ4UEyo187Xk0ey95RWXO7JLdotbw9/B0qxzdt1CMig08FAKnZ60qg4Y53Z1FXcYwbCreHUIIWc2PrDv9VQHTJn5BrHGdVVEbcEVK/ad7wKHFdywuykaqDn6iIhISnv0+HMgfcno5VZejq0tRjAFKJdDlj6MX6a00UH1ylYPDQlZP3R4eDL06OJX490BvOug37Wd7YNKg5c0mH7lsQvCnhjZyuuqRuIywFpPoh5qeG1/nxPEtpEbKz3VT0FcWnp7sYHe2f9DYqTE5Cww8ZtRFn1fBmeg5DD89GTiLj5VdYyMIoKr30ElPiByZvexU8NdizP6XaPa/hEx7wchrjFliFqFG1rxLaeJ99aKgvG7aZ7Fk=
- secure: sEaDznnwssHYeUtEY+xTwJsMR5p6rs2hMFOZgev72qqLeoNNzBTYf+S8O5Pbw1mLoZXzMicFMMq2r6plTyTdfexUzIwX0yLU2+s6v1xS6sAoV6DFXW+tr3wzPFvU7M/EUedfnALR5KLpZAXCe0oiZLEhD6ZP0WpVQp7EBtPvK5oQZVQ5V1qaaIjAlyerJP0FQyhYmLSdH0pXWdQT6ZR5h/kcQuVeJLxuQv69MCnh6+ySXh4Yc3U7dJ1gzMT4i3ddjp7jZ2polbrC3cLSMcS1KVzBS4RARv+vwrcowMvn91GFbl0fgUfu9EhRyXJTqPHG5HMZu8yyY9SXb5s+Vt4ens4WUPvUGlY7TwLkaEmmzK1tzoTJP3Lt56wOrocljt6WPQW7W/odzoVXNOAOux4w7lS29LSMjfFrXFIMh/08wG4BE9cyCPCzY8PN4y1ZAKPmB2x6arsviZOij6zbRwXkzsuqEu+YSrcGvBtQAVpgikIAFb8vzqIrlcj+ztgfuMBNgM2U203+cthDfrtlAe2Romz/Jod3tQYXbtXT367SHEDRbFfOIF5UbRqvcq0HlRG1cLTwXiLauMXViAnQ9z8RVGTcik0lWw4M8+kNENYXt+oC8wL71QqX1Zu1oZUduEH5j1c9hu6bB00lYeihXlngLjRxStDAL+mPhmbKWFyEknk=

after_success:
- ls
- pwd
- curl --ftp-create-dirs -T ./bin/main -u $FTP_USER:$FTP_PASSWORD ftp://ease-62q56ueo.cloudapp.net
