language: go

go:
  - 1.5

branches:
  only:
    - master
    - deployment

before_script:
  #  Install and run RethinkDB
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list;
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -;
  - sudo apt-get update;
  - sudo apt-get -y install rethinkdb;
  - rethinkdb &
