language: go
go:
- 1.5
branches:
  only:
  - master
  - deployment
before_script:
- echo -e "Host ease-62q56ueo.cloudapp.net\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
#  Install and run RethinkDB
- wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -;
- wget -qO rethink.deb http://download.rethinkdb.com/apt/pool/precise/main/r/rethinkdb/rethinkdb_2.1.3~0precise_amd64.deb
- sudo dpkg -i rethink.deb
- sudo apt-get -y install -f
- rethinkdb --version
- sudo cp /etc/rethinkdb/default.conf.sample /etc/rethinkdb/instances.d/instance1.conf
- sudo /etc/init.d/rethinkdb restart

before_install:
- openssl aes-256-cbc -K $encrypted_cab47c9f148d_key -iv $encrypted_cab47c9f148d_iv -in deploy_key.pem.enc -out .travis/deploy_key.pem -d

after_success:
- eval "$(ssh-agent -s)" #start the ssh agent
- chmod 600 .travis/deploy_key.pem # this key should have push access
- ssh-add .travis/deploy_key.pem
- git remote add deploy felttrip@ease-62q56ueo.cloudapp.net:/home/felttrip/git/web-backend
- git push deploy

