language: go

go:
  - 1.5

branches:
  only:
    - master
    - deployment

before_script:
  #  Install and run RethinkDB
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -;
  - wget -qO rethink.deb http://download.rethinkdb.com/apt/pool/precise/main/r/rethinkdb/rethinkdb_2.1.3~0precise_amd64.deb
  - sudo dpkg -i rethink.deb
  - sudo apt-get -y install -f
  - sudo cp /etc/rethinkdb/default.conf.sample /etc/rethinkdb/instances.d/instance1.conf
  - sudo /etc/init.d/rethinkdb restart
