# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
    # Every Vagrant development environment requires a box.
    # We will be using ubuntu 14.04 LST
    config.vm.box = "ubuntu/trusty64"

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    # Change this if you are having issues with IP collisions
    #config.vm.network "private_network", ip: "192.168.50.10"

    # Ease web server port:
    config.vm.network "forwarded_port", guest: 3000, host: 3000
    config.vm.network "forwarded_port", guest: 3001, host: 3001

    # Sync socket server
    config.vm.network "forwarded_port", guest: 8000, host: 8000
    # Sync web server
    config.vm.network "forwarded_port", guest: 8001, host: 8001

    # Rethinkdb config port:
    config.vm.network "forwarded_port", guest: 8080, host: 8080

    # Share an additional folder to the guest VM. The first argument is
    # the path on the host to the actual folder. The second argument is
    # the path on the guest to mount the folder. And the optional third
    # argument is a set of non-required options.
    config.vm.synced_folder "../", "/home/vagrant/go/src/github.com/EaseApp/web-backend" do |folder|
        folder.owner = "vagrant"
    end
    config.vm.provider "virtualbox" do |vb|
        # Customize the amount of memory on the VM:
        vb.memory = "1512"
    end

    # Provisioning
    config.vm.provision "bootstrap", type: "shell" do |s|
        s.path = "scripts/bootstrap.sh"
    end
    config.vm.provision "rethinkSetup", type: "shell" do |s|
        s.path = "scripts/rethinkSetup.sh"
    end
    config.vm.provision "wrapUp", type: "shell" do |s|
        s.path = "scripts/wrapUp.sh"
    end

end
